# **다양한 방식으로 array 생성하기 **

In [1]:
import numpy as np

In [32]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
b = np.array([[2, 3, 4], [5, 6, 7]])
b

array([[2, 3, 4],
       [5, 6, 7]])

In [37]:
c = np.array([(1, 2, 3), (4, 5,  6)])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
d = np.zeros((3, 4))
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
e = np.zeros([3, 4])
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [60]:
f = np.ones((2, 3, 1), dtype=np.int16)
f

array([[[1],
        [1],
        [1]],

       [[1],
        [1],
        [1]]], dtype=int16)

In [61]:
g = np.ones((2, 3, 2), dtype=np.int16)
g

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int16)

In [62]:
h = np.ones((2, 3, 3), dtype=np.int16)
h

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [63]:
i = np.ones((2, 3, 4), dtype=np.int16)
i

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [64]:
j = np.ones((2, 3, 5), dtype=np.int16)
j

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)

In [65]:
k = np.ones((2, 3, 6), dtype=np.int16)
k

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]], dtype=int16)

empty: 랜덤하게 메모리 상태에 따라 달라지는 array 생성

In [66]:
np.empty((2, 3))

array([[4.68567976e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])