# **다양한 방식으로 array 생성하기 **

In [2]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
b = np.array([[2, 3, 4], [5, 6, 7]])
b

array([[2, 3, 4],
       [5, 6, 7]])

In [6]:
c = np.array([(1, 2, 3), (4, 5,  6)])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
d = np.zeros((3, 4))
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
e = np.zeros([3, 4])
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
f = np.ones((2, 3, 1), dtype=np.int16)
f

array([[[1],
        [1],
        [1]],

       [[1],
        [1],
        [1]]], dtype=int16)

In [10]:
g = np.ones((2, 3, 2), dtype=np.int16)
g

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int16)

In [11]:
h = np.ones((2, 3, 3), dtype=np.int16)
h

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [12]:
i = np.ones((2, 3, 4), dtype=np.int16)
i

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [13]:
j = np.ones((2, 3, 5), dtype=np.int16)
j

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)

In [14]:
k = np.ones((2, 3, 6), dtype=np.int16)
k

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]], dtype=int16)

# empty: 랜덤하게 메모리 상태에 따라 달라지는 array 생성

In [15]:
np.empty((2, 3))

array([[4.65755326e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

# **10~30까지 5의 배수 출력**

In [18]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

# 0~1, 0~2, 0~3 사이 0.3의 배수 출력

In [29]:
np.arange(0, 1, 0.3)

array([0. , 0.3, 0.6, 0.9])

In [30]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [34]:
np.arange(0, 3, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7])