Dimensional reconstruction & argmax practice

In [24]:
import numpy as np

arange로 0~9 출력

In [25]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

reshape로 5x2차원으로 전환

In [26]:
b = a.reshape(5, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

flatten을 활용하여 다시 1차원으로 전환

In [28]:
c = b.flatten()
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

argmax로 가장 높은 수 출력

In [32]:
d = c.argmax()
d

9