<a href="https://colab.research.google.com/github/dtype2100/numpy/blob/master/numpy%EB%A1%9C_%ED%96%89%EB%A0%AC_%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

행렬을 쓰고 싶으면, array매서드를 쓰고, 파라미터로 리스트를 넘겨주면 됨. 행렬을 만들고 싶으면 2차원 배열을 쓰면 됨.

In [ ]:
A = np.array([
          [1, -1, 2],
          [3, 2, 2],
          [4, 1, 2],
          [7, 5, 6]
])

A #4x3 행렬

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [ ]:
B = np.array([
              [0, 1],
              [-1, 3],
              [5, 2]
])

B #3x2 행렬

array([[ 0,  1],
       [-1,  3],
       [ 5,  2]])

In [ ]:
C = np.random.rand(3, 5) #3 x 5 행렬

C

array([[0.14498032, 0.40246257, 0.47882077, 0.31056814, 0.15108488],
       [0.5724359 , 0.76935219, 0.06417865, 0.32488806, 0.24507711],
       [0.626986  , 0.39666042, 0.0680381 , 0.21755582, 0.42155107]])

In [ ]:
D = np.zeros((2, 4)) #zeros 는 괄호를 2개 써야 작동

D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [ ]:
A[0][2] #파이썬은 0부터 시작하기 때문

2

In [ ]:
A[0][5] #범위를 넘어서는 값을 쓰면 오류가 나옴

IndexError: ignored